version: '3.9'

services:
  xtralife-server:
    image: xtralife/xtralife-server:v4.2.4
    ports:
     - "2000:2000"

    volumes:
     - ./config:/server/config
     - ./logs:/server/logs

    environment:
      NODE_ENV: production

    links:
      - redis:redis
      - mongodb:mongodb
      - elastic:elastic

  xtralife-dashboard:
    image: xtralife/xtralife-dashboard:v4.1.14
    ports:
     - "3000:3000"

    volumes:
     - ./configDashboard:/dashboard/configDashboard

    environment:
      NODE_ENV: production

    links:
      - redis:redis
      - mongodb:mongodb
      - elastic:elastic

  redis:
    image: redis:7
    volumes:
      - ./data/redis:/data

  mongodb:
    image: mongo
    volumes:
     - ./data/db:/data/db
     - ./data/configdb:/data/configdb

  elastic:
    image: elasticsearch:5
    volumes:
     - ./data/elastic:/usr/share/elasticsearch/data
